### ISSUE TITLE
Docker Anope isn't loading configuration files

### ISSUE THREAD

**Issue by domiluci** [anope/docker#38]
So I was successfully able to set up and configure Anope as an _executable_ on my _Windows PC_, and then connect that executable Anope into my ngIRCd server being hosted on a _NanoPC-T6_ running _OpenMediaVault/Debian_ with _Docker_ support. But I want to run Anope as a Docker instance, as well as ngIRCd, **_all on the NanoPC-T6,_** as my goal is a portable solution where everything is wrapped up in the NanoPC-T6.

However, Docker Anope _(the one on the T6)_ is giving me grief. It'll run fine if I don't use conf files and just specify the settings in the _compose file_ as follows...:
```
services:
  anope:
    image: anope/anope
    container_name: anope
    environment:
      - PUID=${APPUSER_PUID}
      - PGID=${APPUSER_PGID}
      - TZ=${TIME_ZONE_VALUE}
      - ANOPE_UPLINK_IP=${IRC_LANIP}
      - ANOPE_UPLINK_PORT=${IRC_PORT}
      - ANOPE_UPLINK_PASSWORD=${IRC_PASS}
      - ANOPE_SERVICES_NAME=${IRC_SVCNAME}
      - ANOPE_SERVICES_VHOST=${IRC_SVCNAME}
    volumes:
      - ${PATH_TO_APPDATA}/anope:/data
    restart: unless-stopped
```

...But it will never connect to my ngIRCd server as Docker Anope is set by default to connect to InspIRCd, and I can only change that with services.conf, and it's not using my services.conf file. And I'm not switching IRCd just to resolve this.

Now here is the content of my _compose file_ for Docker Anope when trying to use a services.conf file...:
```
services:
  anope:
    image: anope/anope
    container_name: anope
    environment:
      - PUID=${APPUSER_PUID}
      - PGID=${APPUSER_PGID}
      - TZ=${TIME_ZONE_VALUE}
    volumes:
      - ${PATH_TO_CONFIG}/anope:/anope/conf
      - ${PATH_TO_APPDATA}/anope:/data
    restart: unless-stopped
```

...And here's the _error_ when trying to use Docker Anope with a services.conf file:
```
anope  | [Dec 18 23:23:14 2024] Anope 2.0.17, build #1, compiled 01:33:03 Dec 16 2024
anope  | [Dec 18 23:23:14 2024] Using configuration file conf/services.conf
anope  | [Dec 18 23:23:14 2024] File conf/services.conf could not be opened.
anope  | [Dec 18 23:23:14 2024] *** Support resources: Read through the services.conf self-contained
anope  | [Dec 18 23:23:14 2024] *** documentation. Read the documentation files found in the 'docs'
anope  | [Dec 18 23:23:14 2024] *** folder. Visit our portal located at https://www.anope.org/. Join
anope  | [Dec 18 23:23:14 2024] *** our support channel on /server irc.teranova.net channel #anope.
anope  | [Dec 18 23:23:14 2024] Configuration file failed to validate
```

It doesn't seem to be a permissions error as I'm running Docker Anope with an admin level user with every permission possible. And the (sub)directories and files all have appropriate permissions and access rights set. None of my other Docker instances are having any issues, especially with read/write access, so I'm at a loss. And the services.conf file I was using with Docker Anope works with Anope executable on my Windows PC, so I'm at a loss there too.

I could really use some help with this, because this is killing me LOL, and I'd like to profusely thank anyone who supplies it in advance. So thank you.
